# ============================================================
# Custom Launch Template cho MNG
# ============================================================
# Lý do PHẢI custom (KHÔNG dùng Default LT auto-generated by MNG):
#   1. user_data MIME nodeadm: override maxPods=110 (Prefix Delegation)
#   2. metadata_options: enforce IMDSv2 (HttpTokens=required)
#   3. block_device_mappings: gp3 + encrypted (default LT = gp2 unencrypted)
#   4. tag_specifications: dán tag governance lên EC2 instance + EBS volume
#
# Pitfall (memory project_eks_prefix_delegation.md): Default LT KHÔNG sửa
# được sau khi MNG tạo → phải Custom LT từ đầu.
#
# IMPORTANT: KHÔNG set image_id (AMI). MNG quản lý AMI version theo
# ami_type + cluster_version. Set AMI ở đây = MNG mất khả năng auto-rotate
# AMI khi có security patch.
# ============================================================

resource "aws_launch_template" "node" {
  name        = "${local.name_prefix}-lt"
  description = "Launch template for EKS MNG ${var.node_group_name} on cluster ${local.cluster_name}"

  # ----------------------------------------------------------
  # User data — MIME multipart NodeConfig override maxPods=110
  # ----------------------------------------------------------
  user_data = base64encode(local.user_data_mime)

  # ----------------------------------------------------------
  # Metadata options — IMDSv2 enforced
  # ----------------------------------------------------------
  # http_tokens=required → IMDSv2 only (block legacy IMDSv1)
  # http_put_response_hop_limit=2 → cho pod trong container access metadata
  #   (IRSA pod không cần, nhưng workload legacy vẫn có thể dùng)
  # http_endpoint=enabled → bật endpoint (kubelet cần đọc instance ID/region)
  metadata_options {
    http_tokens                 = "required"
    http_put_response_hop_limit = 2
    http_endpoint               = "enabled"
    instance_metadata_tags      = "enabled"
  }

  # ----------------------------------------------------------
  # Block device mapping — root volume gp3 50GB encrypted
  # ----------------------------------------------------------
  # AL2023 root device path = /dev/xvda
  # gp3 baseline 3000 IOPS + 125 MB/s throughput (free tier IOPS).
  # encrypted=true + KHÔNG set kms_key_id → dùng AWS-managed `aws/ebs`
  # (workload data đi PVC riêng có CMK; root vol chỉ có OS+image cache).
  # delete_on_termination=true: node terminate = vol cleanup, không cost lưu trữ.
  block_device_mappings {
    device_name = "/dev/xvda"

    ebs {
      volume_type           = "gp3"
      volume_size           = var.disk_size_gb
      iops                  = 3000
      throughput            = 125
      encrypted             = true
      delete_on_termination = true
    }
  }

  # ----------------------------------------------------------
  # Monitoring — detailed monitoring 1-min CloudWatch (default 5-min)
  # ----------------------------------------------------------
  # +$2.10/instance/month nhưng cho HPA scaling reaction nhanh hơn.
  # Cân nhắc lab: tắt cũng OK vì 3 node ổn định, 5-min đủ.
  monitoring {
    enabled = false
  }

  # ----------------------------------------------------------
  # Tag specifications — dán tag governance lên EC2 + EBS
  # ----------------------------------------------------------
  # AWS pattern: LT-level tag NOT auto-propagate xuống EC2 instance + volume.
  # Phải spec từng resource_type. EKS MNG sẽ MERGE tag MNG-level vào đây.
  tag_specifications {
    resource_type = "instance"
    tags = merge(local.common_tags, {
      Name      = "${local.name_prefix}-node"
      Component = "eks-mng-node"
    })
  }

  tag_specifications {
    resource_type = "volume"
    tags = merge(local.common_tags, {
      Name      = "${local.name_prefix}-node-vol"
      Component = "eks-mng-volume"
    })
  }

  tag_specifications {
    resource_type = "network-interface"
    tags = merge(local.common_tags, {
      Name      = "${local.name_prefix}-node-eni"
      Component = "eks-mng-eni"
    })
  }

  # ----------------------------------------------------------
  # LT version lifecycle
  # ----------------------------------------------------------
  # update_default_version=true: bump lên version mới = default mới luôn,
  # MNG tự pickup khi rolling update.
  update_default_version = true

  # Tag cho chính LT resource
  tags = merge(local.common_tags, {
    Component = "eks-mng-launch-template"
  })

  lifecycle {
    create_before_destroy = true
  }
}
